# This Playbook deploys artifactory!
---
- hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Instal roles
      command: ansible-galaxy install -r requirements.yml --force

  roles:
    - { role: nginx}
    - { role: artifactory }
